on:
  push:
    branches: [main]
  pull_request:

name: clippy

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FrancisRussell/ferrous-actions@v1.1.0
        with:
          command: install-rustup
          profile: minimal
      - uses: FrancisRussell/ferrous-actions@v1.1.0
        with:
          command: cargo clippy
          args: -- -D warnings
          annotations: true
